discussions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(\d+)/$',
        views.discussion,
        name='discussion_details'
        ),
    url(r'^create/(\d+)/$',
        views.create_discussion,
        name='create_discussion'
        ),
]

pyEdu/urls.py
from django.conf.urls import include, url
from courses import views
import discussions

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', views.index, name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/logout/', views.user_logout, name='adminlogout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^course/', include('courses.urls')),
    url(r'^discussion/', include('discussions.urls')),
    url(r'^create_discussion/(\d+)/(\d+)/(\d+)/$',
        discussions.views.create_discussion,
        name='create_discussion'
        ),
    # url(r'^login/', 'django.contrib.auth.views.login'),
]

discussions/models.py
from django.db import models
from django.forms import ModelForm
from courses.models import User, Unit
from django.core.urlresolvers import reverse


class Discussion(models.Model):
    user = models.ForeignKey(User)
    unit = models.ForeignKey(Unit)
    summary = models.CharField(
        'Összefoglaló',
        max_length=100,
        help_text='A kérdés tömör, egy soros összefoglalója, '
        'ami a felsorolások esetén látszik.')
    question = models.TextField(
        'Kérdés',
        max_length=500,
        help_text='Itt részletezzen mindent, '
        'ami a kérdés szempontjából fontos! '
        'A kérdés az összefoglaló nélkül, '
        'önmagában is értelmes legyen.'
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

#    def get_absoulte_url(self):
#       return reverse(
#            'unit',
#            args=(str(i) for i in
#                  (self.lesson.course.id,
#                   self.lesson.serial,
#                   self.serial)
#                  )
#        )

    def get_absolute_url(self):
        return reverse('discussion_details', args=[str(self.id)])


class Answer(models.Model):
    discussion = models.ForeignKey(Discussion)
    user = models.ForeignKey(User)
    text = models.TextField(
        'Válasz szövege',
        max_length=500,
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']


class DiscussionForm(ModelForm):
    class Meta:
        model = Discussion
        fields = ['summary', 'question']


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text']

discussions/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from discussions.models import DiscussionForm, Discussion, AnswerForm
from django.http import HttpResponseRedirect
# from django.form import formset_factory
from courses.models import Unit


@login_required
def create_discussion(request, unit_id):
    unit = Unit.objects.get(id=unit_id)
    if request.method == 'POST':
        form = DiscussionForm(request.POST)
        if form.is_valid():
            discussion = form.save(commit=False)
            discussion.unit = unit
            discussion.user = request.user.user
            discussion.save()
            return HttpResponseRedirect(unit.get_absolute_url())
    else:
        form = DiscussionForm()
    return render(
        request,
        'discussions/create_discussion.html',
        {'form': form, 'unit': unit}
    )


@login_required
def discussion(request, discussion_id):
    discussion = Discussion.objects.get(id=discussion_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.discussion = discussion
            answer.user = request.user.user
            answer.save()
            form = AnswerForm()
    else:
        form = AnswerForm()
    return render(
        request,
        'discussions/discussion.html',
        {'form': form, 'discussion': discussion}
    )

discussions/templates/discussions/create_discussion.html
{% extends "pyEdu/base.html" %}
{% block title %} &ndash; Kérdésfelvetés ehhez: {{unit.title}}{% endblock %}

{% block jumbotron %}
<h2>Kérdezzen a unithoz</h2>

<div class="answer_list">A unit címe: {{unit.title}}</div>
{% endblock jumbotron %}

{% block content %}
<form method="post" action="">{% csrf_token %}
<table style="width:100%;">
    <tr><td>{{form.as_table}}</td></tr>
</table>
<input type="submit" value="Beküldés" class="btn btn-warning btn-lg" role="button"/>
</form>
{% endblock content %}

discussions/templates/discussions/discussion.html
{% extends "pyEdu/base.html" %}
{% load tz %}

{% block jumbotron %}
<div class="answer_title">{{discussion.summary}}</div>
<div class="answer_list">Kérdezte: {{discussion.user.get_name}}<br />
{{discussion.timestamp}}</div>

<a href="{{discussion.unit.get_absolute_url}}" class="btn btn-warning btn-lg" role="button">Vissza a leckéhez</a>
{% endblock jumbotron %}

{% block content %}
<div class="answer_question">{{discussion.question}}</div>
<div class="disc_list">
    {% for answer in discussion.answer_set.all %}
    <div class="row answers">
	<div class="col-xs-4 col-sm-6 answering">{{answer.user.get_name}}</div>
    <div class="col-xs-8 col-sm-6 answering">{{answer.timestamp|localtime|date:"Y.m.d. H:i:s"}}</div>
	<div class="row">
	    <div class="col-sm-12">
		{{answer.text}}
	    </div>
	</div>
    </div>
    {% endfor %}
</div>

<div>
    <form method="post" action="">{% csrf_token %}
	<table>
	    <tr><td>{{form.as_table}}</td></tr>
	    <tr><td></td><td style="text-align:right;"><input type="submit" value="Válaszom!"  class="btn btn-warning btn-lg" role="button"/></td>
	    </tr>
	</table>
    </form>
</div>
{% endblock content%}

discussions/templates/discussions/discussion_list.html
{% load tz %}
{% block content %}
    <table class="table table-hover">
	{% for discussion in unit.discussion_set.all %}
	<tr>
	    <td class="warning"><a href="{% url "discussion_details" discussion.id %}">{{ discussion.summary }}</a></td>
	    <td class="warning">{{ discussion.user.get_name }}</td>
        <td class="warning">{{ discussion.timestamp|localtime|date:"Y.m.d. H:i:s"}}</td>
	    <td class="warning">{{ discussion.answer_set.count }}
		válasz</td></tr>
	{% endfor %}
    </table>
{% endblock content %}